print("I have many hobbies.")
print("I like to code.")
print("I like playing and watching soccer.")
print("I like playing and watching cricket.")
print("These are some of the many hobbies that I have.")